---
- name: Install and configure Prometheus and Node Exporter
  hosts: all
  become: yes
  vars:
    zinit_services_dir: /etc/zinit
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Install Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present

    - name: Ensure zinit services directory exists
      file:
        path: "{{ zinit_services_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure scrape configs directory exists
      file:
        path: /etc/prometheus/scrape_configs
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yaml
        content: |
          global:
            scrape_interval: 60s

          remote_write:
            - url: "{{ prometheus_remote_write_url }}"
              basic_auth:
                username: "{{ prometheus_remote_write_user }}"
                password: "{{ prometheus_remote_write_password }}"

          scrape_configs:
            - job_name: 'node'
              static_configs:
                - targets: ["{{ inventory_hostname }}:9100"]

          scrape_config_files:
            - /etc/prometheus/scrape_configs/*.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Create zinit service file for prometheus
      copy:
        dest: "{{ zinit_services_dir }}/prometheus.yaml"
        content: |
          exec: /usr/bin/prometheus
            --config.file=/etc/prometheus/prometheus.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Create zinit service file for node-exporter
      copy:
        dest: "{{ zinit_services_dir }}/node-exporter.yaml"
        content: |
          exec: /usr/bin/prometheus-node-exporter
        owner: root
        group: root
        mode: "0644"

    - name: Start prometheus service with zinit
      command: zinit monitor prometheus
      register: monitor_result_prometheus
      ignore_errors: yes
      changed_when: monitor_result.rc == 0

    - name: Start node-exporter service with zinit
      command: zinit monitor node-exporter
      register: monitor_result_node_exporter
      ignore_errors: yes
      changed_when: monitor_result.rc == 0

    - name: Restart service if it's already monitored
      command: zinit stop prometheus && zinit start prometheus
      when: monitor_result_prometheus.rc != 0

    - name: Restart service if it's already monitored
      command: zinit stop node-exporter && zinit start node-exporter
      when: monitor_result_node_exporter.rc != 0
